name = "sveltia-cms-auth"
main = "src/index.js"
compatibility_date = "2023-03-24"
# account_id = "Ov23lio8tPeR2PNm2TqO"

[vars]
GITLAB_CLIENT_ID = "Ov23lio8tPeR2PNm2TqO"
GITLAB_CLIENT_SECRET = "742b2b33db213329959570bda7f6c436f68bb6be"
